/*
 * Copyright (C) 2018 mgarcia.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package VIEW.Cadastros;

import CONTROLE.DAO.ManutencaoDAO;
import ENTIDADES.Manutencao;
import ENTIDADES.Veiculo;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mgarcia
 */
public class NovaManutencao extends javax.swing.JFrame {

    Veiculo veiculo;

    /**
     * Creates new form NovaManutencao
     */
    public NovaManutencao(Veiculo v) {
        this.veiculo = v;
        initComponents();
    }

    public NovaManutencao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diabox = new javax.swing.JComboBox<>();
        mesbox = new javax.swing.JComboBox<>();
        anobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kmF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ValorPecasF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ValorServF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServF = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Manutenção");

        diabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Dia","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"}));
        diabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaboxActionPerformed(evt);
            }
        });

        mesbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Mes","janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"}));

        String[] anos = new String[100];
        Date d = new Date();
        int today = d.getYear() + 1900;
        int aux = 1;
        anos[0] = "Ano";
        while (aux < 99) {
            anos[aux] = "" + today;
            aux ++;
            today--;
        }
        anobox.setModel(new javax.swing.DefaultComboBoxModel<>(anos));

        jLabel1.setText("Data da Manutenção");

        jLabel2.setText("Quilometragem");

        jLabel3.setText("Despesa com Peças");

        jLabel4.setText("Despesa com Serviço");

        jLabel5.setText("Descrição do Serviço");

        ServF.setColumns(20);
        ServF.setRows(5);
        jScrollPane1.setViewportView(ServF);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/img/salvar16x16.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diabox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesbox, 0, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anobox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kmF)
                            .addComponent(ValorPecasF)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(ValorServF)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kmF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ValorPecasF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ValorServF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void diaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean validador = true;

        if (diabox.getSelectedIndex() == 0 || mesbox.getSelectedIndex() == 0
                || anobox.getSelectedIndex() == 0) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Preencha uma data válida");
        }

        if (kmF.getText().isEmpty()) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Preencha um valor para quilometragem");
        }

        try {
            if (Integer.parseInt(kmF.getText()) < 0) {
                validador = false;
                JOptionPane.showMessageDialog(null, "valor inválido em quilometragem");
            }
        } catch (Exception e) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Digite apenas numeros inteiros "
                    + "no campo quilometragem");
        }
        //////////
        if (ValorPecasF.getText().isEmpty()) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Preencha um valor para "
                    + "Despesa com Peças");
        }

        try {
            if (Double.parseDouble(ValorPecasF.getText()) < 0) {
                validador = false;
                JOptionPane.showMessageDialog(null, "valor inválido em "
                        + "Despesa Com Peças");
            }
        } catch (Exception e) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Digite apenas numeros "
                    + "separados por '.' no campo quilometragem");
        }
        ////////////////////
        if (ValorServF.getText().isEmpty()) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Preencha um valor para "
                    + "Despesa com Serviço");
        }

        try {
            if (Double.parseDouble(ValorServF.getText()) < 0) {
                validador = false;
                JOptionPane.showMessageDialog(null, "valor inválido em "
                        + "Despesa Com Serviço");
            }
        } catch (Exception e) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Digite apenas numeros "
                    + "separados por '.' no campo Despesa com Serviço");
        }
        /////////
        if (ServF.getText().isEmpty()) {
            validador = false;
            JOptionPane.showMessageDialog(null, "Preencha a descrição do serviço");
        }

        //////////
        if (validador) {

            Manutencao m = new Manutencao();
            ManutencaoDAO dao = new ManutencaoDAO();

            String dd = diabox.getSelectedItem().toString();
            String MM = mesbox.getSelectedItem().toString();
            String yyyy = anobox.getSelectedItem().toString();

            switch (MM) {
                case "janeiro":
                    MM = "01";
                    break;
                case "fevereiro":
                    MM = "02";
                    break;
                case "março":
                    MM = "03";
                    break;
                case "abril":
                    MM = "04";
                    break;
                case "maio":
                    MM = "05";
                    break;
                case "junho":
                    MM = "06";
                    break;
                case "julho":
                    MM = "07";
                    break;
                case "agosto":
                    MM = "08";
                    break;
                case "setembro":
                    MM = "09";
                    break;
                case "outubro":
                    MM = "10";
                    break;
                case "novembro":
                    MM = "11";
                    break;
                case "dezembro":
                    MM = "12";
                    break;
            }
            String data = yyyy + "-" + MM + "-" + dd;
            try {
                m.setData(data);
            } catch (ParseException ex) {
                Logger.getLogger(NovaManutencao.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao converter a data. nada foi salvo.");
                dispose();
            }

            m.setKm(Integer.parseInt(kmF.getText()));
            m.setServico(ServF.getText());
            m.setValorPecas(Double.parseDouble(ValorPecasF.getText()));
            m.setValorServ(Double.parseDouble(ValorServF.getText()));
            m.setVeiculo(this.veiculo.getIdVeiculo());

            int z = JOptionPane.showConfirmDialog(null, "Confirma esta "
                    + "Manutenção para o Veículo " + veiculo.toString() + " ?");

            if (z == 0) {

                try {
                    dao.salvar(m);
                    JOptionPane.showMessageDialog(null, "Manutenção registrada");
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(NovaManutencao.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro ao registrar Manutenção\n" + ex);
                } catch (IOException ex) {
                    Logger.getLogger(NovaManutencao.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro de entrada e saida "
                            + "ao registrar Manutenção\n" + ex);
                }
            } else if (z == 1) {
                JOptionPane.showMessageDialog(null, "Ação cancelada.");
                dispose();
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaManutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ServF;
    private javax.swing.JTextField ValorPecasF;
    private javax.swing.JTextField ValorServF;
    private javax.swing.JComboBox<String> anobox;
    private javax.swing.JComboBox<String> diabox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kmF;
    private javax.swing.JComboBox<String> mesbox;
    // End of variables declaration//GEN-END:variables
}
