/*
 * Copyright (C) 2018 mgarcia.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package VIEW.Consultas;

import CONTROLE.DAO.AbastecimentoDAO;
import CONTROLE.DAO.CombustivelDAO;
import CONTROLE.DAO.RendimentoDAO;
import CONTROLE.DAO.TrajetoDAO;
import ENTIDADES.Abastecimento;
import ENTIDADES.Combustivel;
import ENTIDADES.Rendimento;
import ENTIDADES.Veiculo;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mgarcia
 */
public class ConsultaRendimento extends javax.swing.JDialog {

    ArrayList<Rendimento> lista;
    RendimentoDAO Rdao;
    AbastecimentoDAO Adao;
    CombustivelDAO Cdao;
    TrajetoDAO Tdao;
    Veiculo veiculo;

    /**
     * Creates new form ConsultaRendimento
     */
    public ConsultaRendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ConsultaRendimento(java.awt.Frame parent, boolean modal, Veiculo v)
            throws IOException, SQLException {
        super(parent, modal);
        Rdao = new RendimentoDAO();
        Adao = new AbastecimentoDAO();
        Cdao = new CombustivelDAO();
        Tdao = new TrajetoDAO();
        
        lista = Rdao.getAll(v.getIdVeiculo());
        initComponents();
        VeiculoLabel.setText("Veículo pesquisado: "+v.toString());
    }

    public Object[][] getArray() {
        int length = lista.size();
        Object[][] matrix = new String[length][6];

        Abastecimento ab = new Abastecimento();
        String combustivel = "";
        String Trajeto = "";
        
        for (int i = 0; i < length; i++) {
            Rendimento rendimento = lista.get(i);
            try {
                ab = Adao.getById(rendimento.getAbastecimento());
                //JOptionPane.showMessageDialog(this, ""+ab.getValorLitro()); debug
                combustivel = Cdao.getByID(ab.getTipoCombustivel());
                Trajeto = Tdao.getByID(rendimento.getTrajeto());
            } catch (IOException ex) {
                Logger.getLogger(ConsultaRendimento.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro de Entrada e Saida\n" + ex);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(ConsultaRendimento.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro de pesquisa\n" + ex);
                dispose();
            }

            for (int y = 0; y < 6; y++) {
                switch (y) {
                    case 0:
                        matrix[i][y] = ab.getDataAsString();
                        break;
                    case 1:
                        matrix[i][y] = combustivel;
                        break;
                    case 2:
                        Double kml = rendimento.getKmL();
                        matrix[i][y] = String.format("%.2f", kml);
                        break;
                    case 3:
                        Double ckm;
                        ckm = ab.getValorLitro() / rendimento.getKmL();
                        matrix[i][y] = "R$ "+ String.format("%.2f", ckm);
                        break;
                    case 4:
                        matrix[i][y] = Trajeto;
                        break;
                    case 5:
                        matrix[i][y] = rendimento.getArCond();
                        break;
                }
            }

        }
        return matrix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VeiculoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE RENDIMENTOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            getArray(),
            new String [] {
                "Data", "Combustivel", "Km/L", "Custo por Km", "Trajeto", "Ar Condicionado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(90);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(110);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(160);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(200);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(300);
        }

        VeiculoLabel.setText("Veiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(VeiculoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VeiculoLabel))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaRendimento dialog = new ConsultaRendimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VeiculoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
