/*
 * Copyright (C) 2018 mgarcia.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package VIEW;

import CONTROLE.DAO.CombustivelDAO;
import CONTROLE.DAO.TrajetoDAO;
import CONTROLE.VerificadorBD;
import ENTIDADES.Combustivel;
import ENTIDADES.Trajeto;
import VIEW.Cadastros.CadastrarVeiculo;
import VIEW.Cadastros.NovoAbastecimento;
import ENTIDADES.Usuario;
import ENTIDADES.Veiculo;
import VIEW.Cadastros.CadastrarPosto;
import VIEW.Cadastros.NovaManutencao;
import VIEW.Consultas.ConsultaAbastecimentos;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mgarcia
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario usuario;
    Veiculo veiculo;
    Boolean Validador; //trava as janelas ate q o usuario cadastre um posto e um veiculo

    /**
     * Creates new form TelaPrincipal
     */
    public void TelaPrincipal() {
        initComponents();
    }

    public TelaPrincipal(Usuario u) {
        this.usuario = u;
        try {
            this.Validador = VerificadorBD.Verifica(u);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro de entrada e saida "
                    + "ao verificar dados\n" + ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao verificar os dados\n" + ex);
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        if (Validador) {
            Novo1.setEnabled(true);
            Novo2.setEnabled(true);
            Novo3.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Antes de usar algumas "
                    + "funcionalidades, é necessário cadastrar ao menos 1 Veículo "
                    + "e ao menos 1 Posto de Combustível.\nEstas opções "
                    + "permanecerão trancadas até que você faça isso.");
            JOptionPane.showMessageDialog(null, "Ao terminar de cadastrar o "
                    + "primeiro veículo e o primeiro Posto, reinicie este "
                    + "programa e as funcionalidades serão destrancadas.");
        }
        if (u.getFrotaSize() > 0) {
            veiculo = u.getFromFrotaByPosition(0);
            LabelAtual.setText("Veiculo Atual: " + veiculo.getMarca()
                    + " Placa " + veiculo.getPlaca());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        LabelAtual = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Novo1 = new javax.swing.JMenuItem();
        Novo2 = new javax.swing.JMenuItem();
        Novo3 = new javax.swing.JMenuItem();
        Novo4 = new javax.swing.JMenuItem();
        Novo5 = new javax.swing.JMenuItem();
        Novo6 = new javax.swing.JMenuItem();
        Novo7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Julius Report");
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setText("Logado como: "+usuario.getLogin());

        String[] carros = new String[usuario.getFrotaSize()];
        for (int i = 0; i < usuario.getFrotaSize(); i++) {
            carros[i] = usuario.getFromFrotaByPosition(i).toString();
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(carros));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        LabelAtual.setText("Veiculo Atual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAtual))
                .addContainerGap())
        );

        jMenu1.setText("Novo");

        Novo1.setText("Registrar novo Abastecimento");
        Novo1.setEnabled(false);
        Novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo1ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo1);

        Novo2.setText("Registrar nova Manutenção");
        Novo2.setEnabled(false);
        Novo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo2ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo2);

        Novo3.setText("Registrar Novos Gastos");
        Novo3.setEnabled(false);
        jMenu1.add(Novo3);

        Novo4.setText("Cadastrar novo tipo de Trajeto");
        Novo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo4ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo4);

        Novo5.setText("Cadastrar novo tipo de Combustivel");
        Novo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo5ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo5);

        Novo6.setText("Cadastrar Veículo");
        Novo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo6ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo6);

        Novo7.setText("Cadastrar Posto de Combustivel");
        Novo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Novo7ActionPerformed(evt);
            }
        });
        jMenu1.add(Novo7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        jMenuItem6.setText("Consultar historico de Abastecimentos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Consultar historico de Manutenção");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Consultar histórico de outros gastos ");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Consultar histórico de consumo");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        jMenuItem10.setText("Análise de Consumo por Combustível");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Analise de Consumo por tipo de Trajeto");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Analise de gastos mensais");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Analise de gastos por período");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sistema");

        jMenuItem15.setText("Configurar Banco de dados..");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Sair..");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 247, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo1ActionPerformed
        new NovoAbastecimento(usuario, veiculo).setVisible(true);
    }//GEN-LAST:event_Novo1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int id;
        id = jComboBox1.getSelectedIndex();
        veiculo = usuario.getFromFrotaByPosition(id);
        LabelAtual.setText("Veiculo Atual: " + veiculo.getTipo() + " "
                + veiculo.getMarca() + ", Placa "
                + veiculo.getPlaca());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Novo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo6ActionPerformed
        new CadastrarVeiculo(usuario).setVisible(true);
    }//GEN-LAST:event_Novo6ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new ConsultaAbastecimentos(usuario, veiculo).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        new Configuracoes().setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void Novo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo7ActionPerformed
        new CadastrarPosto().setVisible(true);
    }//GEN-LAST:event_Novo7ActionPerformed

    private void Novo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo4ActionPerformed
        Trajeto trajeto = new Trajeto();
        TrajetoDAO dao = new TrajetoDAO();
        String nome = JOptionPane.showInputDialog(null, "Digite o nome do novo trajeto");
        if (!nome.isEmpty()) {
            trajeto.setNome(nome);
            try {
                dao.salvar(trajeto);
                JOptionPane.showMessageDialog(null, "Trajeto registrado.");
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao registrar trajeto\n" + ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro de entrada e saida "
                        + "ao registrar trajeto\n" + ex);
            }
        }

    }//GEN-LAST:event_Novo4ActionPerformed

    private void Novo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo5ActionPerformed
        Combustivel c = new Combustivel();
        CombustivelDAO dao = new CombustivelDAO();
        String nome = JOptionPane.showInputDialog(null, "Digite o nome do novo Combustivel");
        if (!nome.isEmpty()) {
            c.setNome(nome);
            try {
                dao.salvar(c);
                JOptionPane.showMessageDialog(null, "Combustivel registrado.");
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao registrar Combustivel\n" + ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro de entrada e saida "
                        + "ao registrar Combustivel\n" + ex);
            }
        }
        
        
    }//GEN-LAST:event_Novo5ActionPerformed

    private void Novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Novo2ActionPerformed
        new NovaManutencao(this.veiculo).setVisible(true);
    }//GEN-LAST:event_Novo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAtual;
    private javax.swing.JMenuItem Novo1;
    private javax.swing.JMenuItem Novo2;
    private javax.swing.JMenuItem Novo3;
    private javax.swing.JMenuItem Novo4;
    private javax.swing.JMenuItem Novo5;
    private javax.swing.JMenuItem Novo6;
    private javax.swing.JMenuItem Novo7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
